/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPanierRouteImport } from './routes/_authenticated/panier'
import { Route as AuthenticatedLivreurRouteImport } from './routes/_authenticated/livreur'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedCommandesRouteImport } from './routes/_authenticated/commandes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDriverOrdersRouteImport } from './routes/_authenticated/driver.orders'
import { Route as AuthenticatedDriverConversationsRouteImport } from './routes/_authenticated/driver.conversations'
import { Route as AuthenticatedCommandeIdRouteImport } from './routes/_authenticated/commande.$id'
import { Route as AuthenticatedAdminOptionsRouteImport } from './routes/_authenticated/admin/options'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin/menu'
import { Route as AuthenticatedAdminLivreursRouteImport } from './routes/_authenticated/admin/livreurs'
import { Route as AuthenticatedAdminLivreurStatsRouteImport } from './routes/_authenticated/admin/livreur-stats'
import { Route as AuthenticatedOrdersOrderIdTrackingRouteImport } from './routes/_authenticated/orders.$orderId.tracking'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanierRoute = AuthenticatedPanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivreurRoute = AuthenticatedLivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandesRoute = AuthenticatedCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverOrdersRoute =
  AuthenticatedDriverOrdersRouteImport.update({
    id: '/driver/orders',
    path: '/driver/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriverConversationsRoute =
  AuthenticatedDriverConversationsRouteImport.update({
    id: '/driver/conversations',
    path: '/driver/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandeIdRoute = AuthenticatedCommandeIdRouteImport.update({
  id: '/commande/$id',
  path: '/commande/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOptionsRoute =
  AuthenticatedAdminOptionsRouteImport.update({
    id: '/options',
    path: '/options',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLivreursRoute =
  AuthenticatedAdminLivreursRouteImport.update({
    id: '/livreurs',
    path: '/livreurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLivreurStatsRoute =
  AuthenticatedAdminLivreurStatsRouteImport.update({
    id: '/livreur-stats',
    path: '/livreur-stats',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedOrdersOrderIdTrackingRoute =
  AuthenticatedOrdersOrderIdTrackingRouteImport.update({
    id: '/orders/$orderId/tracking',
    path: '/orders/$orderId/tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/compte': typeof CompteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/commandes': typeof AuthenticatedCommandesRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/panier': typeof AuthenticatedPanierRoute
  '/admin/livreur-stats': typeof AuthenticatedAdminLivreurStatsRoute
  '/admin/livreurs': typeof AuthenticatedAdminLivreursRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/options': typeof AuthenticatedAdminOptionsRoute
  '/commande/$id': typeof AuthenticatedCommandeIdRoute
  '/driver/conversations': typeof AuthenticatedDriverConversationsRoute
  '/driver/orders': typeof AuthenticatedDriverOrdersRoute
  '/orders/$orderId/tracking': typeof AuthenticatedOrdersOrderIdTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/compte': typeof CompteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/commandes': typeof AuthenticatedCommandesRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/panier': typeof AuthenticatedPanierRoute
  '/admin/livreur-stats': typeof AuthenticatedAdminLivreurStatsRoute
  '/admin/livreurs': typeof AuthenticatedAdminLivreursRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/options': typeof AuthenticatedAdminOptionsRoute
  '/commande/$id': typeof AuthenticatedCommandeIdRoute
  '/driver/conversations': typeof AuthenticatedDriverConversationsRoute
  '/driver/orders': typeof AuthenticatedDriverOrdersRoute
  '/orders/$orderId/tracking': typeof AuthenticatedOrdersOrderIdTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/compte': typeof CompteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/commandes': typeof AuthenticatedCommandesRoute
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/livreur': typeof AuthenticatedLivreurRoute
  '/_authenticated/panier': typeof AuthenticatedPanierRoute
  '/_authenticated/admin/livreur-stats': typeof AuthenticatedAdminLivreurStatsRoute
  '/_authenticated/admin/livreurs': typeof AuthenticatedAdminLivreursRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/options': typeof AuthenticatedAdminOptionsRoute
  '/_authenticated/commande/$id': typeof AuthenticatedCommandeIdRoute
  '/_authenticated/driver/conversations': typeof AuthenticatedDriverConversationsRoute
  '/_authenticated/driver/orders': typeof AuthenticatedDriverOrdersRoute
  '/_authenticated/orders/$orderId/tracking': typeof AuthenticatedOrdersOrderIdTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/compte'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin'
    | '/commandes'
    | '/complete-profile'
    | '/dashboard'
    | '/livreur'
    | '/panier'
    | '/admin/livreur-stats'
    | '/admin/livreurs'
    | '/admin/menu'
    | '/admin/options'
    | '/commande/$id'
    | '/driver/conversations'
    | '/driver/orders'
    | '/orders/$orderId/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/compte'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin'
    | '/commandes'
    | '/complete-profile'
    | '/dashboard'
    | '/livreur'
    | '/panier'
    | '/admin/livreur-stats'
    | '/admin/livreurs'
    | '/admin/menu'
    | '/admin/options'
    | '/commande/$id'
    | '/driver/conversations'
    | '/driver/orders'
    | '/orders/$orderId/tracking'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/compte'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/commandes'
    | '/_authenticated/complete-profile'
    | '/_authenticated/dashboard'
    | '/_authenticated/livreur'
    | '/_authenticated/panier'
    | '/_authenticated/admin/livreur-stats'
    | '/_authenticated/admin/livreurs'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/options'
    | '/_authenticated/commande/$id'
    | '/_authenticated/driver/conversations'
    | '/_authenticated/driver/orders'
    | '/_authenticated/orders/$orderId/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CompteRoute: typeof CompteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panier': {
      id: '/_authenticated/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof AuthenticatedPanierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreur': {
      id: '/_authenticated/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof AuthenticatedLivreurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commandes': {
      id: '/_authenticated/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof AuthenticatedCommandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver/orders': {
      id: '/_authenticated/driver/orders'
      path: '/driver/orders'
      fullPath: '/driver/orders'
      preLoaderRoute: typeof AuthenticatedDriverOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver/conversations': {
      id: '/_authenticated/driver/conversations'
      path: '/driver/conversations'
      fullPath: '/driver/conversations'
      preLoaderRoute: typeof AuthenticatedDriverConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commande/$id': {
      id: '/_authenticated/commande/$id'
      path: '/commande/$id'
      fullPath: '/commande/$id'
      preLoaderRoute: typeof AuthenticatedCommandeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/options': {
      id: '/_authenticated/admin/options'
      path: '/options'
      fullPath: '/admin/options'
      preLoaderRoute: typeof AuthenticatedAdminOptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/livreurs': {
      id: '/_authenticated/admin/livreurs'
      path: '/livreurs'
      fullPath: '/admin/livreurs'
      preLoaderRoute: typeof AuthenticatedAdminLivreursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/livreur-stats': {
      id: '/_authenticated/admin/livreur-stats'
      path: '/livreur-stats'
      fullPath: '/admin/livreur-stats'
      preLoaderRoute: typeof AuthenticatedAdminLivreurStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/orders/$orderId/tracking': {
      id: '/_authenticated/orders/$orderId/tracking'
      path: '/orders/$orderId/tracking'
      fullPath: '/orders/$orderId/tracking'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLivreurStatsRoute: typeof AuthenticatedAdminLivreurStatsRoute
  AuthenticatedAdminLivreursRoute: typeof AuthenticatedAdminLivreursRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminOptionsRoute: typeof AuthenticatedAdminOptionsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLivreurStatsRoute: AuthenticatedAdminLivreurStatsRoute,
  AuthenticatedAdminLivreursRoute: AuthenticatedAdminLivreursRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedAdminOptionsRoute: AuthenticatedAdminOptionsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCommandesRoute: typeof AuthenticatedCommandesRoute
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLivreurRoute: typeof AuthenticatedLivreurRoute
  AuthenticatedPanierRoute: typeof AuthenticatedPanierRoute
  AuthenticatedCommandeIdRoute: typeof AuthenticatedCommandeIdRoute
  AuthenticatedDriverConversationsRoute: typeof AuthenticatedDriverConversationsRoute
  AuthenticatedDriverOrdersRoute: typeof AuthenticatedDriverOrdersRoute
  AuthenticatedOrdersOrderIdTrackingRoute: typeof AuthenticatedOrdersOrderIdTrackingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCommandesRoute: AuthenticatedCommandesRoute,
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLivreurRoute: AuthenticatedLivreurRoute,
  AuthenticatedPanierRoute: AuthenticatedPanierRoute,
  AuthenticatedCommandeIdRoute: AuthenticatedCommandeIdRoute,
  AuthenticatedDriverConversationsRoute: AuthenticatedDriverConversationsRoute,
  AuthenticatedDriverOrdersRoute: AuthenticatedDriverOrdersRoute,
  AuthenticatedOrdersOrderIdTrackingRoute:
    AuthenticatedOrdersOrderIdTrackingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CompteRoute: CompteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
